<a href="https://colab.research.google.com/github/Matchuuuuu/Linear-Algebra-58019/blob/main/Matrix_and_Its_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array ([[6,-3],[2,3]])
print(A)

print(B)

[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]


In [11]:
# 1. sum = A + B
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array ([[6,-3],[2,3]])
sum = A + B
print(sum)

[[ 1 -3]
 [ 6  4]]


In [12]:
# 2. difference1 = B - A
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array ([[6,-3],[2,3]])
difference1 = B - A
print(difference1)

[[11 -3]
 [-2  2]]


In [13]:
# 3. difference2 = A - B 
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array ([[6,-3],[2,3]])
difference2 = A - B
print(difference2)

[[-11   3]
 [  2  -2]]
