<a href="https://colab.research.google.com/github/Matchuuuuu/Linear-Algebra-58019/blob/main/Mideterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

In [48]:
import numpy as np 
S = np.array ([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]) 
print(S) 

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)

In [47]:
import numpy as np
A = np.triu([[5,7,1,5,3],[1,4,2,9,4],[7,1,8,7,5],[6,8,2,4,2],[4,2,1,5,9]])
print(A)

[[5 7 1 5 3]
 [0 4 2 9 4]
 [0 0 8 7 5]
 [0 0 0 4 2]
 [0 0 0 0 9]]


Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

In [50]:
import numpy as np 
S = np.array([[1,2,3,4,5],[2,1,2,3,4],[3,2,1,2,3],[4,3,2,1,2],[5,4,3,2,1]])
print(S)

[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [49]:
import numpy as np
C = np.array ([[1,2,3],
               [2,3,3],
               [3,4,-2]])
i = np.linalg.inv(C)
print(i)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [41]:
import numpy as np
C = np.array ([[1,2,3],
               [2,3,3],
               [3,4,-2]])
d = np.linalg.det(C)
print(int(d))

5


In [40]:
import numpy as np
eq = np.array([[5,4,1],
               [10,9,4],
               [10,13,15]])

const = np.array([[[3.4],
                   [8.8],
                   [19.2]]])
ro = np.linalg.inv(eq) @ const
print(ro)

[[[0.2]
  [0.4]
  [0.8]]]
