<a href="https://colab.research.google.com/github/Matchuuuuu/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1

In [22]:
import numpy as np

A = np.array ([[1,2,3],[4,5,6]])
B = np.array ([[1,2],[3,4],[5,6]])
C = np.array ([[1,2,3],[4,5,6],[7,8,9]])
D = np.array ([[1,2],[3,4]])
print(A, " \n") 
print(B, " \n")
print(C, " \n")
print(D, " \n")

[[1 2 3]
 [4 5 6]]  

[[1 2]
 [3 4]
 [5 6]]  

[[1 2 3]
 [4 5 6]
 [7 8 9]]  

[[1 2]
 [3 4]]  



In [50]:
#Number 1
dot = np.dot(A,B)
print   (dot)

[[22 28]
 [49 64]]


In [21]:
#Number 2 
D + D


array([[2, 4],
       [6, 8]])

In [51]:
# Number 3
C * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

Problem 2 

In [53]:
import numpy as np
A = np.array ([5,3,-1])

print(A.size)

print(type(A))

print(A.shape)

print(A.ndim)

3
<class 'numpy.ndarray'>
(3,)
1
