<a href="https://colab.research.google.com/github/Matchuuuuu/Linear-Algebra-58019/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Representing Vectors

In [ ]:
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])
print ('Vector A is' , A)
print ('Vector B is' , B)

Vector A is [4 3]
Vector B is [ 2 -5]


**Describing Vectors in NumPy**

In [ ]:
### Checking shapes
### Shapes tells us how many rows and columns are there
ball1 = np.array ([1,2,3])
ball2 = np.array ([0.1,-1])
pool = np.array([ball1 , ball2])
pool.shape
pool.ndim


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """


1

In [ ]:
U = np.array ([[1,2,3],[4,5,6]])
U


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
U = np.array ([[1,2,3],[4,5,6]])
U
U.size

6

Space

Vector space are mathematical objects that abstractly capture the geometry and algebra of linear equations

Addition of Vectors


In [ ]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
sum = addend1 + addend2
sum 

array([1, 1, 0])

In [ ]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
resultant = np.add(addend1,addend2)
resultant

array([1, 1, 0])

Subtraction of Vectorss

In [22]:
diff = addend1 - addend2
diff

array([-1, -1,  0])

In [24]:
diff2 = np.subtract(addend1,addend2)
diff2

array([-1, -1,  0])

Multiplication of Vectors 

In [25]:
A = np.array([1,5,8,9])
S = 5*A
S

array([ 5, 25, 40, 45])

In [31]:
A = np.array([2,3])
B = np.array([1,7])
cross = np.cross(A,B)
print(cross)

11


In [33]:
A = np.array([2,3,4])
B = np.array([1,7,1])
cross = np.cross(A,B)
print(cross)

[-25   2  11]
