<a href="https://colab.research.google.com/github/Matchuuuuu/Linear-Algebra-58019/blob/main/Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix Algebra

In [1]:
#numpy
import numpy as np
a = np.array([1,2,3]) #Example of 1x3 matrix.
print(a)

[1 2 3]


In [3]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]]) #Example of 2x3 matrix.
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np
c = np.array([[1,2,3],[4,5,6],[7,8,9]]) #Example of 3x3 matrix.
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
import numpy as np
d = np.full((3,3),7) #Full matrix
print(d)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [10]:
import numpy as np
e = np.array([[1,2,3],[4,5,6],[7,8,9]]) #Square matrix
print(e)
e = np.diagonal([[1,2,3],[4,5,6],[7,8,9]]) 
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [11]:
import numpy as np
f = np.eye(3) #Identity matrix.
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
import numpy as np
g = np.zeros((2,2)) #Zero matrix
print(g)

[[0. 0.]
 [0. 0.]]


In [15]:
import numpy as np
h = np.empty((0,12)) #Empty matrix.
print(h)

[]


In [16]:
import numpy as np
d = np.full((3,3),7) #Addition + Full matrix
print(d+d)

[[14 14 14]
 [14 14 14]
 [14 14 14]]


In [17]:
import numpy as np
d = np.full((3,3),7) #Subtraction + Full matrix
print(d-d)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
